require "owodunni.options"
require "owodunni.keymaps"
require "owodunni.plugins"
require "owodunni.colorscheme"
require "owodunni.cmp"
require "owodunni.lsp"
require "owodunni.telescope"
require "owodunni.treesitter"
